// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl1RfAjNZXI7Ih-2tM9RpjJCFXXbcfa2E',
    appId: '1:532519393347:web:98d1be438d7dc36c089cf6',
    messagingSenderId: '532519393347',
    projectId: 'opencloudhealth',
    authDomain: 'opencloudhealth.firebaseapp.com',
    storageBucket: 'opencloudhealth.appspot.com',
    measurementId: 'G-Q7EBW8ER80',
  );  

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl1RfAjNZXI7Ih-2tM9RpjJCFXXbcfa2E',
    appId: '1:532519393347:web:98d1be438d7dc36c089cf6',
    messagingSenderId: '532519393347',
    projectId: 'opencloudhealth',
    authDomain: 'opencloudhealth.firebaseapp.com',
    storageBucket: 'opencloudhealth.appspot.com',
    measurementId: 'G-Q7EBW8ER80',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFqOeLVAvV4-HywVHOJ4QdAk0v7Z4W-_Q',
    appId: '1:532519393347:android:21cfa900a1614550089cf6',
    messagingSenderId: '532519393347',
    projectId: 'opencloudhealth',
    storageBucket: 'opencloudhealth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhKvEMkrnVTOZg41KSootwKT8Sb7CzPKs',
    appId: '1:532519393347:ios:82f5d5a3066c4048089cf6',
    messagingSenderId: '532519393347',
    projectId: 'opencloudhealth',
    storageBucket: 'opencloudhealth.appspot.com',
    iosClientId: '532519393347-fs3163tqeqp9ifjhudtda3vuoj1lhivv.apps.googleusercontent.com',
    iosBundleId: 'com.example.openCloudHealth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhKvEMkrnVTOZg41KSootwKT8Sb7CzPKs',
    appId: '1:532519393347:ios:1eceff86e39a2940089cf6',
    messagingSenderId: '532519393347',
    projectId: 'opencloudhealth',
    storageBucket: 'opencloudhealth.appspot.com',
    iosClientId: '532519393347-fev67tvhe2oeo7htoc4a06lfsaf34f1q.apps.googleusercontent.com',
    iosBundleId: 'com.example.openCloudHealth.RunnerTests',
  );
}
